version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    volumes:
      - bakery_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"
volumes:
   bakery_db: